version: '3.8'
services:
  crm-api:
    container_name: crm-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: redecv8@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rooot282
    ports:
      - "5050:80"
    volumes:
      - pgadmin-d–∞ta:/var/lib/pgadmin

volumes:
  postgres:
    name: crm-db
