version: '3.8'
services:
  nest-api:
    container_name: crm-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - postgres
    env_file:
      - .ENV
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nest-api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email redecv9@gmail.com -d initcrm.ru --agree-tos
    

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dirrnd@hype.rnd
      PGADMIN_DEFAULT_PASSWORD: superuser228
    ports:
      - "5050:80"
    volumes:
      - pgadminData:/var/lib/pgadmin

volumes:
  postgres:
  pgadminData: